{
 "title": "cmffs",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "hostalive",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "ping4",
     "query": "SELECT last(\"state\") FROM \"ping4\" WHERE \"hostname\" =~ /^cmffs/ AND $timeFilter",
     "select": [
      [
       { "params": [ "state" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "ping4",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "s", "label": "rta" }
   ],
   "targets": [
    {
     "alias": "rta",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ping4",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^cmffs/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "rta" }
     ]
    },
    {
     "alias": "pl",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ping4",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^cmffs/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "pl" }
     ]
    }
   ]
  },
  {
   "title": "ping6",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "s", "label": "rta" }
   ],
   "targets": [
    {
     "alias": "rta",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ping6",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^cmffs/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "rta" }
     ]
    },
    {
     "alias": "pl",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ping6",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^cmffs/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "pl" }
     ]
    }
   ]
  },
  {
   "title": "disk \\Services-Backup",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "gigabytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disk_smb",
     "query": "SELECT ((max-value)/1024/1024/1024) FROM \"disk_smb\" WHERE \"hostname\" =~ /^cmffs/ AND \"service\" =~ /Services-Backup$/ AND $timeFilter"
    }
   ]
  },
  {
   "title": "disk \\Services-NoBackup",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "gigabytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disk_smb",
     "query": "SELECT ((max-value)/1024/1024/1024) FROM \"disk_smb\" WHERE \"hostname\" =~ /^cmffs/ AND \"service\" =~ /Services-NoBackup$/ AND $timeFilter"
    }
   ]
  }
 ]
}