#!/bin/bash

. /opt/helpers

influx -execute "CREATE DATABASE icinga2"
influx -execute "CREATE USER icinga2 WITH PASSWORD 'icinga' WITH ALL PRIVILEGES" -database="icinga2"

icinga2 feature enable perfdata influxdb

cat >/etc/icinga2/features-available/influxdb.conf <<-END
library "perfdata"
object InfluxdbWriter "influxdb" {
    host = "127.0.0.1"
    port = 8086
    database = "icinga2"
    username = "icinga2"
    password = "icinga"
}
END
